### ISSUE TITLE
有一个屏幕亮度的BUG

### ISSUE THREAD

**Issue by LinJiaXing1102** [HJaycee/JCBrightness#1]
当跳转到下一个需要高亮的控制器，等待差不多10s左右返回上级页面，亮度依旧还是高亮。

发现到高亮的控制器的时候，过差不多十秒会执行 saveDefaultBrightness 方法，导致存储了亮度是高亮的亮度。

**Comment by RichDaddyCashMany** [comment]
好的，我有空看下！可以的话你也可以帮忙解决下！

**Comment by LinJiaXing1102** [comment]
发现是先注册了屏幕变亮的通知 ，然而亮度还在缓慢的变亮，导致变为全亮的时候，会存储一次高亮的亮度~

**Comment by LinJiaXing1102** [comment]
本来想等作者修改，自己懒得动哈哈哈
今天有空就看了一下，有一个初步的方案，对线程不是很了解，所以方法有些辣鸡...

在ios9与ios7中，方法是没有问题的
在ios8和ios10中，就会出现这个问题，具体我下面详细说一下。
在初始化这个类的时候（+ (void)initialize），我们注册了UIScreenBrightnessDidChangeNotification这个通知。在ios8和ios10中，在结束屏幕亮度变成设定值约5s左右之后，会再次执行saveDefaultBrightness（通知事件）这个方法，导致再次存储了当前的亮度。
经过观察，发现如果屏幕的设置值不设置为1(也就是最亮)，会导致上述错误。
所以我就修改了+ (void)graduallySetBrightness:(CGFloat)value里面的一小段代码
[UIScreen mainScreen].brightness = brightness + i * step;
 改为
[UIScreen mainScreen].brightness = (i == times) ? ((value > brightness) ? value : _currentBrightness) :(brightness + i * step);
而且，在调用+ (void)graduallySetBrightness:(CGFloat)value这个方法的时候，值只能设置1(也就是最亮)。

抱歉，功夫不是很到家，只能提供这个很辣鸡的方法。

**Comment by RichDaddyCashMany** [comment]
恩，谢谢你啊

**Comment by huangzhifei** [comment]
这个代码很有意思，我改了改，修复上面说的bug，增加了一些监听。作者可以看看，我发起一个pull request。 @linjiaxing1992 @HJaycee

**Comment by huangzhifei** [comment]
思路：主要是延迟绑定监听
